### ISSUE TITLE
Attribute error?

### ISSUE THREAD

**Issue by mh-tan** [ksahlin/BESST_RNA#9]
Hi,

I mapped my RNA reads to my assembly with Hisat2 and fed it into BESST_RNA. However, I got the following error.

----------
Starting scaffolding with library:  DARW_heart.hisat2.sorted.bam
Parsing BAM file...
Computing parameters not set by user...

Mean of library set to: No mean calc since RNA reads
Standard deviation of library set to: No std calc since RNA reads
-T (library insert size threshold) set to:  20000
-k set to (Scaffolding with contigs larger than):  500
Number of links required to create an edge:  5
Read length set to:  81.4333193897
Relative weight of dominating link set to (default=3):  3

L50:  28205 N50:  30511 Initial contig assembly length:  3235877917
Nr of contigs/scaffolds included in scaffolding: 519724
Total time elapsed:  5.56891298294
Traceback (most recent call last):
  File "/home/munhua/installers/BESST_RNA-master/src/Main.py", line 247, in <module>
    options.mapquality)
  File "/home/munhua/installers/BESST_RNA-master/src/Main.py", line 79, in Main
    (G, Contigs, Scaffolds, F, param) = CG.PE(Contigs, Scaffolds, F, Information, output_dest, C_dict, param)      #Create graph, single out too short contigs/scaffolds and store them in F
  File "/home/munhua/installers/BESST_RNA-master/src/CreateGraph.py", line 198, in PE
    G.edge[(scaf1, scaf_side1)][(scaf2, scaf_side2)]['nr_links'] += 1
AttributeError: 'Graph' object has no attribute 'edge'

Any ideas or solutions would be much appreciated.

Thanks
Mun

**Comment by ksahlin** [comment]
Hi Mun,

Yes, besst_rna does not support the module networkx versions 2 or later. you need to reinstall  networkx < 2, for example version 1.9.
